FROM kalilinux/kali-rolling

RUN apt update && apt install -y \
    tshark \
    crackmapexec \
    responder \
    python3-impacket \
    openssh-client \
    git \
    inotify-tools \
    rsync \
    txt2html \
    && apt clean

RUN mkdir -p /data/input /data/output /root/.ssh

# Lien symbolique pour que le script fonctionne
RUN ln -s /data/output /output && ln -s /data/input /input

WORKDIR /data

COPY analyze.sh /analyze.sh
COPY squirrel_key /root/.ssh/squirrel_key
RUN chmod 600 /root/.ssh/squirrel_key
RUN chmod +x /analyze.sh

CMD ["/analyze.sh"]
